name: Build application

on: [push, pull_request]

jobs:
 ubuntu-gcc-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        sudo apt-get update
        sudo apt install libomp-dev
        cd Poisson_Equation/sln
        cmake .
        cmake --build . --config Release
    - name: Run test
      shell: bash
      run: |
        cd Poisson_Equation/sln/Dirichlet_Problem
        ./Dirichlet_Problem
